### ISSUE TITLE
use salt-event-hub

### ISSUE THREAD

**Issue by twerkmeister** [scalableminds/hubot#1]
- [x] adjust salt.coffee so it does the appropriate HTTP(S) requests instead of salt-event calls
- [x] use https
- [x] use X-AUTH-Token header for authentication (read from environment variable)

<a href="https://timer.scm.io/repos/53df5790350000e6016747c0/issues/1/create?referer=github" target="_blank">Log Time</a>

**Comment by speedcom** [comment]
Commits: 54bb967, 74dacaf, 22343f7

**Comment by speedcom** [comment]
I still have trouble with request (404 error) to flask server because of superagent lib which is super annyoying (or it's just me) -

**Comment by twerkmeister** [comment]
improvements:
- [x] remove duplication of sending code

**Comment by twerkmeister** [comment]
Hey Mati (@speedcom)
just noticed that there are two more things that could be improved:
- [x] url creation conceptionally belongs to fireAdminEvent, this would also avoid code duplication
- [x] Prior to your changes it was only allowed to deploy/start/stop services in their respective rooms. Please put that check back in.
